"use client"
import { Roboto } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";
import Head from "next/head";
import { AuthProvider } from "./_components/forms/AuthContext";

const inter = Roboto({ subsets: ["latin"], weight: ['400', '700'] });

// export const metadata = {
//   title: "BlueCollar",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <AuthProvider>
      <html lang="en">
        <Head>
          <link rel="shortcut icon" href="/logo.svg"/>
        </Head>
        <body className={inter.className}>
          <div className="mx-6 md:mx-16">
            <Header/>
          {children}
          </div>
          </body>
      </html>
    </AuthProvider>
  );
}
